### PR TITLE
[Services-269] Separated error log

### PR DESCRIPTION
**Pull request by jcellary**
Added separate error log file for the api-gateway

Pinging @drsnyder

### CODE REVIEW

**Comment by drsnyder** [comment]
How will this work in practice? Can you write a metric via `print` or `ngx.log` in lua and have it picked up?

**Comment by jcellary** [comment]
That's the idea - I tested making invalid requests which nginx automatically reported in api-gateway.error.log file and that got transfered to elasticsearch. For the lua part I tried this:
content_by_lua 'ngx.log(ngx.ERR, "this is a log string from lua")' 
and it got written to the error log file.

**Comment by drsnyder** [comment]
Ok, cool. What about metrics? Are we currently sending only the render times and the counts? Is it possible to log something and have it recorded as a timer?

**Comment by jcellary** [comment]
That can be problematic - currently we simply log the times as reported in the access.log. That gives as information about each request processing time and that enables us to track their total count. If we wanted to introduce custom metrics measured from within lua we would need to create some additional mechanism for that.

**Pull request merged**
