### PR TITLE
Add a simple polling health monitor

### PR DESCRIPTION
**Pull request by drsnyder**
This was a quickly hacked together script to monitor the gateway for either non-200, lengthy, or failed connections to the api-gateway (or an URL really) health check URI.

https://wikia-inc.atlassian.net/browse/SERVICES-769

### CODE REVIEW

**Comment by nmonterroso** [comment]
is `trollius` already installed on the nodes? if so LGTM

**Comment by drsnyder** [comment]
No, probably not. At the moment, we don't really the infrastructure for running something like this continuously. I'm just using it as a diagnostic tool from my laptop / dev box at the moment to see if I can catch it.

**Comment by nmonterroso** [comment]
ah ok, so you'll just `pip install` it? i guess that makes sense, as long as it's installed/run in a virtual environment so we don't pollute the global python installation

**Comment by nmonterroso** [comment]
LGTM shipit

**Pull request merged**
